import { createSlice } from "@reduxjs/toolkit"
import { IReportsPatient } from "../../models/reducers/patients.model"

const initialState: IReportsPatient = {
  id: 0,
  sid: 0,
  pCode: "",
  pName: "",
  pAge: 0,
  pSex: "",
  pAddress: "",
  patientImage: null,
  typeCode: null,
  type: "",
  pPhone: "",
  birthDay: "",
  modality: "",
  diagnose: "",
  assDepartment: "",
  assDoctor: "",
  serviceName: "",
  editById: "",
  lstDrEdit: [],
  editByDrName: "",
  consultByDrName: null,
  aproveById: "",
  aproveByDrName: "",
  aproveByDrPhone: "",
  editByDrPhone: "",
  consultByDrPhone: null,
  aproveByDrAddress: "",
  code: "",
  orgCode: "",
  svState: 0,
  tech: "",
  descImg: "",
  result: "",
  proposal: "",
  timeStr: "",
  userAdd: "",
  aproTime: "",
  hospital: {
    id: 0,
    name: "",
    locate: "",
    hospitalType: 0,
    order: 0,
    areaId: null,
    areaName: null,
    userCreate: null,
    userModify: null,
    createDate: null,
    modifyDate: null,
    status: 0,
  },
  header: {
    id: 0,
    name: "",
    pTitle: "",
    pTitle2: null,
    pHospital: "",
    pDepartment: "",
    pAddress: "",
    pPhone: null,
    pNote: null,
    pLogo: "",
    template: "",
    userCreate: null,
    userModify: null,
    createDate: null,
    modifyDate: null,
    status: null,
  },
  room: "",
  bed: "",
  executor: null,
  typePrint: 0,
  password: "",
  timeAss: "",
  timeEx: "",
  lsvv: null,
  typeOfObject: null,
  drSignImage: "",
  drReadSignImage: "",
  drConsultSignImage: null,
  isPrint: false,
  isEmergency: null,
  orderNumber: null,
  userHis: null,
  indicatedDoctorSignImage: null,
  reExamDay: 0,
  listImgs: [],
  listImgsDesc: [],
  listKeyImgs: [],
  listMainExecutor: [],
  listSubExecutor: [],
  svExCode: null,
  indicatedRoom: null,
  jsonResult: null,
  timePrint: "",
  resultLinkHIS: "",
  extendDescTxt: null,
  dataExtendDescTxt: null,
  sicknessCondition: 0,
}

const reportsPatientSlice = createSlice({
  name: 'reportsPatient',
  initialState,
  reducers: {
    setReportsPatient: (state, action) => {
      state = action.payload
      return state
    },
  },
})

export const { setReportsPatient } = reportsPatientSlice.actions
export default reportsPatientSlice.reducer
